Fix infinite loop bug after YAML_MEMORY_ERROR (psych issue #440)
ruby/psych pull request #526
Opened 2021-10-28 08:39 UTC by khanderson

This is a fix for https://github.com/ruby/psych/issues/440, where there was inconsistent handling of the `parser->error == YAML_MEMORY_ERROR` case.

`parse()` didn't check `parser->error` at all.  `yaml_parser_parse` checked it and exited early, but returned success, so the error wasn't detected at all and the parse loop never terminated.

This change makes `parse` check `parser->error` and raise NoMemoryError.

I can't see an easy way to add test coverage for this; there's no way to set the error member from ruby.  I'd be happy to add that if someone can suggest how.

2021-10-28 08:53 UTC, olleolleolle commented on ext/psych/psych_parser.c
> +	return rb_eNoMemError;
I don't know anything about this, _but_ from this line on, there seems to be formatting differences from the existing code. Do you know how to make them more the same?

2021-10-28 09:10 UTC, khanderson commented on ext/psych/psych_parser.c
> +	return rb_eNoMemError;
I tried to keep this consistent with the surrounding code, which seems to use four spaces for the first level of indentation, and a single tab for the second level.  I guessed that the tab width is 8 for this project.  The diff below is ugly because it indents a block and so adds a bunch of tabs.  Is there a style guide I can look at?

2021-11-09 01:13 UTC, Sarkar44 requested changes
request change

2021-11-09 01:14 UTC, Sarkar44 commented
approve

2021-11-09 01:14 UTC, Sarkar44 commented
marge pull requests

2022-02-16 16:03 UTC, sashakovryga commented
@khanderson Is there any news about this pull request? When will it be merged? 

Do you use your fork? Or did find an alternative solution?

2022-02-16 16:20 UTC, khanderson commented
@sashakovryga, I'm running this fork in a production system, so can confirm that it fixes the issue and hasn't created more. The PR hasn't been merged though.

@olleolleolle @Sarkar44 @tenderlove any chance this could be merged?

2022-02-17 06:42 UTC, sashakovryga commented
> @sashakovryga, I'm running this fork in a production system, so can confirm that it fixes the issue and hasn't created more. The PR hasn't been merged though.
> 
> @olleolleolle @Sarkar44 @tenderlove any chance this could be merged?

Great, I'll try to run this fork on our system. Thanks!

2022-03-29 11:38 UTC, nobu commented on ext/psych/psych_parser.c
> +	return rb_eNoMemError;
How about inserting early-return just after the variable definitions?
```C
    if (parser->error == YAML_MEMORY_ERROR) {
	return rb_eNoMemError;
    }
```

2022-07-14 16:39 UTC, merged